### ISSUE TITLE
if is there a relevant tree-support configuration can be provided?

### ISSUE THREAD

**Issue by zhangjiangzhao123** [ThomasRahm/CuraEngine#10]
Hello, I want to transplant your algorithm in my Demo, but I still don't quite understand the meaning of some setting parameters of this kind of tree support. I have made some mistakes after setting it according to my experience, so I would like to ask if Is there a relevant configuration file about tree-support that can be provided?

**Comment by ThomasRahm** [comment]
I am not sure what you mean. The settings are defined in the fdmprinter.def.json of the UI (not part of this Repository). I appended the fdmprinter.def.json i used for testing the changes i made since this branch updated to CuraEngine 5.3, but the default values do not match the ones in the xmas alpha causing profiles to differ.  
[fdmprinter.def.json.zip](https://github.com/ThomasRahm/CuraEngine/files/11012740/fdmprinter.def.json.zip)

**Comment by zhangjiangzhao123** [comment]
Thanks for the answer to my question. It's very helpful for me!
