### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by pawel54321** [ThomasRahm/CuraEngine#13]
Hello,

Great project! I use all time.

I have only one question. Could you tell me about updates? Is it possible support newest version Cura for your project? I saw new version Cura "layers print nicer".

**Comment by ThomasRahm** [comment]
The reason I did not update this recently, is because it is merged into Cura since 5.4, so if you want to use them just download Cura. Some setting names and the default settings are slightly different so you may need to adapt your settings.

[Link to UltiMaker Cura](https://github.com/Ultimaker/Cura/releases)

**Comment by pawel54321** [comment]
I understand, so If I install new Cura version I need replace new files version Cura with your files?

**Comment by ThomasRahm** [comment]
No.
The Cura tree supports are based on this since 5.4.
You ONLY need to install the new Cura. It already has the same tree supports you know of previous releases of this project.
