### ISSUE TITLE
Idea:  Support points rather than areas.

### ISSUE THREAD

**Issue by Hello1024** [ThomasRahm/CuraEngine#5]
Tree supports currently support *areas*.   However, trees are well suited to supporting specific points.   For example, rather than supporting the whole of an overhanging area, just support the outer corners of the overhang.

This allows regular bridging to be used to print the layer, between the various supports and the already printed object.

This should substantially reduce the amount of support material, but also make the support easier to remove, and surface finish higher, since there will only be contact at critical locations rather than over large areas.

**Comment by ThomasRahm** [comment]
This seems like a great idea, but I tried something like this already some time ago, though I cant recall if it ever made it into a release. It worked by only adding a tip every few mm of every printed line. (Just supporting the outer corners causes issues with concentric bottom pattern) 
I removed it because the quality of the overhangs was slightly worse than overhang supported by support roof and was a bit harder to remove. You can see the last remnants of this system in how the support roof is supported by trees.  
Thinner printed lines (of the roof) result in a better quality than less contact points. It's why I explicitly recommend to use support roof.
