### ISSUE TITLE
Support defect(s) in UltiMaker-Cura-5.3.0-alpha+xmas-linux-modern.AppImage

### ISSUE THREAD

**Issue by vh-xvg** [ThomasRahm/CuraEngine#8]
Thomas, firstly thank you so much for the work you have done on the new tree support. It is simply inspiring to see what an improvement this is over what I'm sure will soon become the legacy tree support. I've tried all of the mainstream slicers with the attached model, and your new support results in by far the best outcome.

Attached is a project file, some screenshots, a cura log, and notes describing a defect in the support for this test case.

**Application Version**
<pre> UltiMaker-Cura-5.3.0-alpha+xmas-linux-modern.AppImage </pre>

**Platform**
<pre> Fedora 37, x86_64 </pre>

**Qt**
<pre> N/A </pre>

**PyQt**
<pre> N/A </pre>

**Display Driver**
<pre>  asus_wmi,i915 </pre>

**Steps to Reproduce**
<pre> Open the attached project. Slice. Inspect the support (inside the model) in layers 732 and upwards. </pre>

**Actual Results**
<p> Looking at layer 732, in the inside space of the model, there is a main support column that is just branching out. To the right of this is a much smaller support column, which is probably not printable, and it starts angling over and doing some sort of support job around layer 850ish. It is so thin and tall though, I doubt it would print (haven't tried it yet).  In higher layers, this skinny support tree appears to mingle with the main support tree, later re-emerging. At layer 1034, a ring of support is printed in mid air, clearly related to the earlier tree but some distance from it, as shown in the attached pictures. This mid air support then continues up, but obviously won't print properly. </p>

**Expected results**
<p> I would expect that all support in this area would grow from the single, main tree inside the model. </p>

**Additional Information**
<p> The following screenshots illustrate the problem(s) described above </p>

[CFFFP_5.3_lhs_inlet7_repaired_pla.3mf.zip](https://github.com/ThomasRahm/CuraEngine/files/10329462/CFFFP_5.3_lhs_inlet7_repaired_pla.3mf.zip)
![lhs_inlet7_support_bug1_732](https://user-images.githubusercontent.com/65583537/210185176-764061ce-1f0c-4ba5-bc7f-7ded0bf20682.png)
![lhs_inlet7_support_bug1_1034](https://user-images.githubusercontent.com/65583537/210185182-cb12d09f-6ca9-40ef-a14d-b85981b21607.png)
![lhs_inlet7_support_bug1_1034_better_view](https://user-images.githubusercontent.com/65583537/210185183-99abfec9-fbdb-4d0b-a734-80735f1110d8.png)
[cura.log.zip](https://github.com/ThomasRahm/CuraEngine/files/10329476/cura.log.zip)

**Comment by ThomasRahm** [comment]
When there is no way to a flat surface, branches will just go down as far as possible. So if the point furthest down is a Support blocker it "rests" on the support blocker. I have not added culling of these branches as i hope to find a better solution in the future (e.g. trying to find a non flat area on the model to rest on). It is an edge-case that rarely comes up, so i have not spent much time on it. 
Try moving the support blocker 20 by 15 mm in y direction, so that it is possible for this sub-branch to reach the main branch, and it should (if `Branch reach limit` it allows, as only branches that violate this setting by the same amount merge) merge with the main branch.

![Result with Support blocker 20 moved slightly](https://user-images.githubusercontent.com/67757218/210231339-73100565-b7e3-46b3-9460-2f5d8c939c22.png)

**Comment by vh-xvg** [comment]
Thanks Thomas. I moved the blocker and it resolved the floating support. I must admit the sloppy support blockers in the database I uploaded were an outcome of fighting with the legacy cura tree support, and I just left them as is when I tried out the new tree support.

I have another issue, I'm going to file a separate report on that.

Thanks, Adrian
